config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :name, :body, presence: true


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Post Saved"
      redirect_to root_path
    else
      flash[:alert] = "There were Errors in creating this post"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "Post Updated"
      redirect_to root_path
    else
      flash[:alert] = "There were Errors in updating this post"
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice] = "Post Deleted"
    else
      flash[:alert] = "There were Errors in deleting this post"
    end
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:name,:body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cuke</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div id="flash-notice">
  <% if flash[:notice] %>
    <div class="flash alert alert-success alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:notice] %>
    </div>
  <% end %>
</div>

<div id="flash-alert">
  <% if alert %>
    <div class="flash alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :body, "Body" %>
  <%= f.text_area :body %>
  <%= f.submit "Submit" %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| %>
  <li><%= link_to post.name, post_path(post) %></li>
  <p>
    <%= post.body %>
    <%= link_to "Delete", post_path(post), method: :delete %>
  </p>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<h1>Show Page</h1>
<h3><%= @post.name %></h3>
<p>
  <%= @post.body %>
</p>